@startuml

enum SportNumber{
    PlayersSize = 10,
    Coaches = PlayersSize,
    Rules = 4,
}

abstract Sport{
    +Players
    +Coaches
    +Rules[]
    +int Score
    +AddScore()
    +Run()
    +Stop()
}

class Football implements Sport{
    +Kick()
}

class Baseball implements Sport{
    +Hit()
}

class Execute{
    +Game(Sport sport)
}

@enduml