@startgantt
saturday are closed
sunday are closed

Project starts the 23th of October 2024

[Week 12: IoT MQTT Programming Part 1 (TCP and WIFI)] as [W1] starts at 2024-10-23 and lasts 1 day
[Week 13: IoT MQTT Programming Part 2 (Adafruit IO)] as [W2] starts 6 days after [W1]'s end and lasts 1 day
[Week 14: Project Design, Requirements, UML and Planning] as [W3] starts 6 days after [W2]'s end and lasts 1 day
[Start Final Project Stage] happens at [W3]'s end
[Week 15: FreeRTOS Programming (Part 3)] as [W4] starts 6 days after [W3]'s end and lasts 1 day
[Week 16: Final Project workshop (Part 1)] as [W5] starts 6 days after [W4]'s end and lasts 1 day
[First Project delivery] happens at [W5]'s end
[Week 17: Final Project workshop (Part 2)] as [W6] starts 6 days after [W5]'s end and lasts 1 day
[Week 18: Final Project workshop (Part 3)] as [W7] starts 6 days after [W6]'s end and lasts 1 day
[End Final Delivery] happens at [W7]'s end
@endgantt
